### PR TITLE
[SDK-1858] Create legacy samsite cookie by default

### LINKED ISSUE #515: Invalid State Error on Ipad  safari and chrome
### Describe the problem

> When logging in with a **loginWithRedirect**, you will be redirected back to your app with code and state values set as URL query parameters. These values are used by **handleRedirectCallback** And this result in Error: Invalid state

 
### Environment

> Please provide the following:

- **Version of `auth0-spa-js` used:** 1.10.0
- **Which browsers have you tested in?** Ipad "Chrome Mobile iOS 83.0.4103 / iOS 12.0.0", "Mobile Safari 12.0.0 / iOS 12.0.0", 
- **Which framework are you using, if applicable (Angular, React, etc):** "React"

### PR DESCRIPTION
**Pull request by adamjmcgrath**
### Description

Add a legacy SameSite cookie (one without SameSite set to 'None') for legacy browsers.

Also adding the option to turn this off (to avoid browser console warning) with the caveat that this will break silent auth for incompatible clients https://www.chromium.org/updates/same-site/incompatible-clients

### References

See https://web.dev/samesite-cookie-recipes/#handling-incompatible-clients
Fixes #515 

### Testing

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

File: src/Auth0Client.ts [hunk 1]
```diff
@@ -128,13 +133,18 @@ export default class Auth0Client {
   private tokenIssuer: string;
   private defaultScope: string;
   private scope: string;
+  private CookieStorage: ClientStorage;
```
Comment (stevehobbsdev) [inline src/Auth0Client.ts:136]: What's the reason for making this Title Case? Could we follow convention for other class-level props?

Comment (adamjmcgrath) [reply src/Auth0Client.ts:136]: I was generally using the convention `SomethingTitleCase = SomeOtherThingTitleCase || YetAnotherThingTitleCase;` - but sure, I can change to camel case

**Review by stevehobbsdev — APPROVED** [review]
