### PR TITLE
Do not use AbortController in the worker if not available

### LINKED ISSUE #675: AbortController is not defined
### Describe the problem

Hi! I initially raised this issue in `@auth0/auth0-react` repository (https://github.com/auth0/auth0-react/issues/173), but for visibility, and because this is the actual package having the issue, I post this issue here as well.

On Firefox 52 (and probably other browsers versions that doesn't support AbortController API), the `getAccessTokenSilently` method will throw this error. It seems like this API is used in `@auth0/auth0-spa-js`, and there is a Polyfill for this API, but it isn't working. And it's probably the case for any browser version that doesn't support natively this API (https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

Here is the stack trace I have when catching errors from the `getAccessTokenSilently`:

```
10:34:13.434 Error: AbortController is not defined
Stack trace:
OAuthError@http://localhost:3000/static/js/0.chunk.js:3816:17
["../../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js"]/</normalizeErrorFn/<@http://localhost:3000/static/js/0.chunk.js:3841:14
["../../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js"]/</Auth0Provider/getAccessTokenSilently</</<@http://localhost:3000/static/js/0.chunk.js:4127:19
step@http://localhost:3000/static/js/0.chunk.js:210:12
verb/<@http://localhost:3000/static/js/0.chunk.js:141:14
rejected@http://localhost:3000/static/js/0.chunk.js:103:14
 1 0.chunk.js:83125:18
	["../../node_modules/react-error-overlay/lib/index.js"]/</</</g/console[e] http://localhost:3000/static/js/0.chunk.js:83125:18
	ExportAuth/</< http://localhost:3000/static/js/main.chunk.js:3009:7
```

### What was the expected behavior?

The `getAccessTokenSilently` should not fail because of AbortController API being undefined on browsers versions that don't support this API natively.

### Reproduction

I'm working on a Private instance in Auth0, so I can't share client id, etc. And it seems that I can't make the examples working locally, but the private repository I'm working on is very simple, so I think you should be able to reproduce it by setting up the example and running it on Firefox 52.

### Environment

- **Version of `auth0-spa-js` used:** 1.13.5, used by `@auth0/auth0-react@1.2.0`
- **Which browsers have you tested in?** Firefox 52, Chromium 65, Safari 11
- **Which framework are you using, if applicable (Angular, React, etc):** React 16.13.1
- **Other modules/plugins/libraries that might be involved:**

### PR DESCRIPTION
**Pull request by stevehobbsdev**
This PR excludes the use of `AbortController` inside the web worker if it is
not natively supported by the browser. Currently, this generates errors if it
is not available, but we wouldn't like to polyfill it due to the size.

I have changed the code to allow browsers that support WebWorker but not AbortController to once again use the web worker.

Tested in Safari 10, 11, 12 and Firefox 52.

Fixes #675

### CODE REVIEW

File: src/Auth0Client.ts [hunk 1]
```diff
@@ -92,8 +92,7 @@ const cacheFactory = (location: string) => {
 /**
  * @ignore
  */
-const supportWebWorker = () =>
-  !isIE11() && !isSafari10() && !isSafari11() && !isSafari12_0();
+const supportWebWorker = () => !isIE11();
```
Comment (stevehobbsdev) [inline src/Auth0Client.ts:95]: @frederikprijck is it fair to say we only added these Safari checks to stop it from using the web worker _purely_ because of `AbortConrtoller`, or were there other factors?

I haven't removed these functions, do you see value in keeping them around or should we remove them?

**Comment by stevehobbsdev** [comment]
Fixing tests now

File: src/Auth0Client.ts (hunk 1 above)
Comment (frederikprijck) [reply src/Auth0Client.ts:95]: It was to fix the AbortController: https://github.com/auth0/auth0-spa-js/issues/594

Comment (frederikprijck) [reply src/Auth0Client.ts:95]: If we revert this, we should test this again on Safari. LMK if you dont have access to BrowserStack, I dont mind testing it.

Comment (stevehobbsdev) [reply src/Auth0Client.ts:95]: Yeah I've tested, versions I tested are in the PR

File: __tests__/Auth0Client/getTokenSilently.test.ts [hunk 2]
```diff
@@ -617,30 +617,6 @@ describe('Auth0Client', () => {
...
-          name: 'Safari 12',
-          userAgent:
-            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15',
-          supported: false
-        },
-        {
-          name: 'Safari 12.1',
-          userAgent:
-            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15',
-          supported: true
```
Comment (stevehobbsdev) [inline __tests__/Auth0Client/getTokenSilently.test.ts:643]: I didn't completely refactor the test here despite there being only 1 browser to test, but we might add to this later so made sense to me to leave it. What do you think? @frederikprijck

Comment (frederikprijck) [reply __tests__/Auth0Client/getTokenSilently.test.ts:643]: Yes I agree!

Comment (stevehobbsdev) [reply __tests__/Auth0Client/getTokenSilently.test.ts:643]: Codecov says otherwise 😂

Comment (frederikprijck) [reply __tests__/Auth0Client/getTokenSilently.test.ts:643]: Ye we need to add one with `supported: true` .. 😬 Or rework it ?

Comment (stevehobbsdev) [reply __tests__/Auth0Client/getTokenSilently.test.ts:643]: I can leave the Safari 12.1 test in, would that help?

Comment (frederikprijck) [reply __tests__/Auth0Client/getTokenSilently.test.ts:643]: I think that could help. Wouldn't make much sense to some degree tho. Because why test only safari 12.1, and not other versions or firefox or ...  ?

Comment (stevehobbsdev) [reply __tests__/Auth0Client/getTokenSilently.test.ts]: I've added a known supported browser in this test, Chrome 76, just to give us that positive and negative angle.

File: src/worker/token.worker.ts [hunk 3]
```diff
@@ -67,7 +71,12 @@ const messageHandler = async ({
 
     if (!response) {
       // If the request times out, abort it and let `fetchWithTimeout` raise the error.
-      abortController.abort();
+      if (abortController) abortController.abort();
+
+      port.postMessage({
+        error: "Timeout when executing 'fetch'"
+      });
```
Comment (frederikprijck) [inline src/worker/token.worker.ts:78]: Why are we adding this?

Comment (stevehobbsdev) [reply src/worker/token.worker.ts:78]: This was mostly for the benefit of the test, to be able to determine that the failure was because of a timeout, but could also be a useful error message on the client regardless. What do you think?

Comment (frederikprijck) [reply src/worker/token.worker.ts:78]: I think this is fine. It rejects the promise using the same error we already have incase it timesout based on the setTimeout.

**Review by frederikprijck — APPROVED** [review]

File: src/worker/token.worker.ts (hunk 3 above)
Comment (stevehobbsdev) [reply src/worker/token.worker.ts:78]: It shouldn't do.. if the timeout is hit, no response will be returned from `Promise.race` and falls into the next block that checks for an empty response, rather than falling into the catch. I could be mistaken; I tried to test for that here: https://github.com/auth0/auth0-spa-js/blob/fix/abort-controller/__tests__/token.worker.test.ts#L146
